# 1. Project Metadata
spring.application.name=CloudShare

# 2. Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudshare_db
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Hibernate / JPA Settings
# 'update' will automatically create/modify tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 4. File Upload Configuration (Crucial for a Drive Clone)
# Default is 1MB, which is too small for most files.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 5. Security / JWT Secret (We will use this in our Security classes)
# Make sure this is at least 32 characters long
cloudshare.jwt.secret=your_very_long_random_and_secure_secret_key_here
cloudshare.jwt.expiration=86400000

# 6. Local Storage Path (Where files will physically sit on your PC)
# Create this folder on your computer first!
file.upload-dir=./uploads

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration